swagger: "2.0"
info:
  version: "1.0"
  title: API VERSIONING EXAMPLE
host: "localhost:10010"
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /user:
    x-swagger-router-controller: user
    get:
      tags:
        - Users
      description: Get one user.
      operationId: getUser
      x-security-scopes:
        - admin
      consumes:
        - application/json
      responses:
        "200":
          description: Success
          schema:
            type: object
            example:
              status: OK
              code: 200
              message: 'Success'
              data:
                status: OK
                code: 200
                message: Success
                data:
                  publicId: 8227b0c0-c059-4520-8537-1af221ed1201
                  firstName: User
                  lastName: User
                  userName: user2501
                  gender: M
                  maritalStatus: M
                  birthDate: 0000-00-00
                  email: username1@gmail.com
                  country: US
                  city: FL
                  province:
                  address:
                  zipCode:
                  phoneNumber:
                  countryCode:
                  lastLogin:
                  createdAt: '2018-12-11T02:14:20.179Z'
                  updatedAt: '2018-12-11T02:14:20.179Z'
                  role:
                    publicId: 6a46de14-489a-4944-b57e-218ab5c44ac1
                    roleName: client
                    createdAt: '2018-12-11T02:02:17.620Z'
                    updatedAt: '2018-12-11T02:02:17.620Z'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        example: Database error
